In [3]:
import pandas as pd

### df.to_dict

In [4]:
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
df = pd.DataFrame(data)

In [12]:
print(df)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [6]:
df.to_dict()

{'A': {0: 1, 1: 2, 2: 3}, 'B': {0: 4, 1: 5, 2: 6}, 'C': {0: 7, 1: 8, 2: 9}}

In [9]:
df.to_dict(orient = 'dict')

{'A': {0: 1, 1: 2, 2: 3}, 'B': {0: 4, 1: 5, 2: 6}, 'C': {0: 7, 1: 8, 2: 9}}

In [8]:
df.to_dict(orient = 'list')

{'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}

In [13]:
print(df.to_dict(orient = 'records'))

[{'A': 1, 'B': 4, 'C': 7}, {'A': 2, 'B': 5, 'C': 8}, {'A': 3, 'B': 6, 'C': 9}]

In [11]:
df.to_dict(orient = 'index')

{0: {'A': 1, 'B': 4, 'C': 7},
 1: {'A': 2, 'B': 5, 'C': 8},
 2: {'A': 3, 'B': 6, 'C': 9}}

### index.level

In [3]:
# MultiIndex 생성
index = pd.MultiIndex.from_tuples([('A', 1), ('A', 2), ('B', 1), ('B', 2)], names=['letter', 'number'])
df = pd.DataFrame({'value': [10, 20, 30, 40]}, index=index)

print(df)

               value
letter number
A      1          10
       2          20
B      1          30
       2          40

In [4]:
df.index

MultiIndex([('A', 1),
            ('A', 2),
            ('B', 1),
            ('B', 2)],
           names=['letter', 'number'])

In [19]:
print(df.index.levels)
print(df.index.names)
print(df.index.get_level_values(0))
print(df.index.get_level_values('letter'))
print(df.swaplevel('letter', 'number').sort_index(level = 'number'))

[['A', 'B'], [1, 2]]
['letter', 'number']
Index(['A', 'A', 'B', 'B'], dtype='object', name='letter')
Index(['A', 'A', 'B', 'B'], dtype='object', name='letter')
               value
number letter
1      A          10
       B          30
2      A          20
       B          40

In [20]:
data = {
        'student_id': [1, 1, 1, 2, 2, 2, 13, 13, 13, 6, 6, 6],
        'student_name': ['Alice', 'Alice', 'Alice', None, None, None, 'John', 'John', 'John', 'Alex', 'Alex', 'Alex'],
        'subject_name': [None, 'Physics', 'Programming', None, 'Physics', 'Programming', None, 'Physics', 'Programming', None, 'Physics', 'Programming'],
        'attended_time': [3.0, 2.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
}

df = pd.DataFrame(data)

In [23]:
df

    student_id student_name subject_name  attended_time
0            1        Alice         None            3.0
1            1        Alice      Physics            2.0
2            1        Alice  Programming            1.0
3            2         None         None            1.0
4            2         None      Physics            0.0
5            2         None  Programming            1.0
6           13         John         None            1.0
7           13         John      Physics            1.0
8           13         John  Programming            1.0
9            6         Alex         None            0.0
10           6         Alex      Physics            0.0
11           6         Alex  Programming            0.0

In [32]:
df.dropna(subset = 'student_name', axis = 'rows')

    student_id student_name subject_name  attended_time
0            1        Alice         None            3.0
1            1        Alice      Physics            2.0
2            1        Alice  Programming            1.0
6           13         John         None            1.0
7           13         John      Physics            1.0
8           13         John  Programming            1.0
9            6         Alex         None            0.0
10           6         Alex      Physics            0.0
11           6         Alex  Programming            0.0